# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_climbed', models.DateField()),
                ('route_climbed', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Climber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_climbs', models.IntegerField(default=0)),
                ('unique_climbs', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('elevation', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('location', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='climb',
            name='climber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cascade_mountain_climber.Climber'),
        ),
        migrations.AddField(
            model_name='climb',
            name='mountain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cascade_mountain_climber.Mountain'),
        ),
    ]
